// ==UserScript==
// @name       Rody WaiGua Programming
// @version    20150613
// @include    http://*.ctb988.com/*  
// @include    http://*.ctb988.net/*  
// @copyright  2014+, CH3CHO <luotingkk@163.com>
// @grant      none
// ==/UserScript==

Array.prototype.contains=function(a){return RegExp(a).test(this)};Array.indexOf||(Array.prototype.indexOf=function(a){for(var e=0;e<this.length;e++)if(this[e]==a)return e;return-1});Array.prototype.contains=function(a){for(var e=this.length;e--;)if(this[e]===a)return!0;return!1};
var Zepto=function(){function a(a){return null==a?String(a):K[S.call(a)]||"object"}function e(J){return"function"==a(J)}function b(a){return null!=a&&a==a.window}function d(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function c(J){return"object"==a(J)}function f(a){return c(a)&&!b(a)&&Object.getPrototypeOf(a)==Object.prototype}function g(a){return p.call(a,function(a){return null!=a})}function q(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,
"$1_$2").replace(/_/g,"-").toLowerCase()}function E(a){return a in L?L[a]:L[a]=new RegExp("(^|\\s)"+a+"(\\s|$)")}function w(a,b){return"number"!=typeof b||T[q(a)]?b:b+"px"}function D(a){return"children"in a?t.call(a.children):h.map(a.childNodes,function(a){return 1==a.nodeType?a:void 0})}function C(a,b,c){for(m in b)c&&(f(b[m])||I(b[m]))?(f(b[m])&&!f(a[m])&&(a[m]={}),I(b[m])&&!I(a[m])&&(a[m]=[]),C(a[m],b[m],c)):b[m]!==n&&(a[m]=b[m])}function y(a,b){return null==b?h(a):h(a).filter(b)}function r(a,
b,c,d){return e(b)?b.call(a,c,d):b}function u(a,b){var c=a.className,d=c&&c.baseVal!==n;return b===n?d?c.baseVal:c:void(d?c.baseVal=b:a.className=b)}function k(a){var b;try{return a?"true"==a||("false"==a?!1:"null"==a?null:/^0/.test(a)||isNaN(b=Number(a))?/^[\[\{]/.test(a)?h.parseJSON(a):a:b):a}catch(c){return a}}function z(a,b){b(a);for(var c in a.childNodes)z(a.childNodes[c],b)}var n,m,h,x,F,G,A=[],t=A.slice,p=A.filter,B=window.document,M={},L={},T={"column-count":1,columns:1,"font-weight":1,"line-height":1,
opacity:1,"z-index":1,zoom:1},H=/^\s*<(\w+|!)[^>]*>/,U=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,l=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,O=/^(?:body|html)$/i,V=/([A-Z])/g,W="val css html text data width height offset".split(" "),N=B.createElement("table"),P=B.createElement("tr"),Q={tr:B.createElement("tbody"),tbody:N,thead:N,tfoot:N,td:P,th:P,"*":B.createElement("div")},X=/complete|loaded|interactive/,Y=/^[\w-]*$/,K={},S=K.toString,v={},R=B.createElement("div"),Z={tabindex:"tabIndex",
readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},I=Array.isArray||function(a){return a instanceof Array};return v.matches=function(a,b){if(!b||!a||1!==a.nodeType)return!1;var c=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(c)return c.call(a,b);var d,c=a.parentNode,
e=!c;return e&&(c=R).appendChild(a),d=~v.qsa(c,b).indexOf(a),e&&R.removeChild(a),d},F=function(a){return a.replace(/-+(.)?/g,function(a,J){return J?J.toUpperCase():""})},G=function(a){return p.call(a,function(b,c){return a.indexOf(b)==c})},v.fragment=function(a,b,c){var d,e,p;return U.test(a)&&(d=h(B.createElement(RegExp.$1))),d||(a.replace&&(a=a.replace(l,"<$1></$2>")),b===n&&(b=H.test(a)&&RegExp.$1),b in Q||(b="*"),p=Q[b],p.innerHTML=""+a,d=h.each(t.call(p.childNodes),function(){p.removeChild(this)})),
f(c)&&(e=h(d),h.each(c,function(a,b){-1<W.indexOf(a)?e[a](b):e.attr(a,b)})),d},v.Z=function(a,b){return a=a||[],a.__proto__=h.fn,a.selector=b||"",a},v.isZ=function(a){return a instanceof v.Z},v.init=function(a,b){var d;if(!a)return v.Z();if("string"==typeof a)if(a=a.trim(),"<"==a[0]&&H.test(a))d=v.fragment(a,RegExp.$1,b),a=null;else{if(b!==n)return h(b).find(a);d=v.qsa(B,a)}else{if(e(a))return h(B).ready(a);if(v.isZ(a))return a;if(I(a))d=g(a);else if(c(a))d=[a],a=null;else if(H.test(a))d=v.fragment(a.trim(),
RegExp.$1,b),a=null;else{if(b!==n)return h(b).find(a);d=v.qsa(B,a)}}return v.Z(d,a)},h=function(a,b){return v.init(a,b)},h.extend=function(a){var b,c=t.call(arguments,1);return"boolean"==typeof a&&(b=a,a=c.shift()),c.forEach(function(c){C(a,c,b)}),a},v.qsa=function(a,b){var c,e="#"==b[0],p=!e&&"."==b[0],f=e||p?b.slice(1):b,k=Y.test(f);return d(a)&&k&&e?(c=a.getElementById(f))?[c]:[]:1!==a.nodeType&&9!==a.nodeType?[]:t.call(k&&!e?p?a.getElementsByClassName(f):a.getElementsByTagName(b):a.querySelectorAll(b))},
h.contains=function(a,b){return a!==b&&a.contains(b)},h.type=a,h.isFunction=e,h.isWindow=b,h.isArray=I,h.isPlainObject=f,h.isEmptyObject=function(a){for(var b in a)return!1;return!0},h.inArray=function(a,b,c){return A.indexOf.call(b,a,c)},h.camelCase=F,h.trim=function(a){return null==a?"":String.prototype.trim.call(a)},h.uuid=0,h.support={},h.expr={},h.map=function(a,b){var c,d,e=[];if("number"==typeof a.length)for(d=0;d<a.length;d++)c=b(a[d],d),null!=c&&e.push(c);else for(d in a)c=b(a[d],d),null!=
c&&e.push(c);return 0<e.length?h.fn.concat.apply([],e):e},h.each=function(a,b){var c;if("number"==typeof a.length)for(c=0;c<a.length&&!1!==b.call(a[c],c,a[c]);c++);else for(c in a)if(!1===b.call(a[c],c,a[c]))break;return a},h.grep=function(a,b){return p.call(a,b)},window.JSON&&(h.parseJSON=JSON.parse),h.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,b){K["[object "+b+"]"]=b.toLowerCase()}),h.fn={forEach:A.forEach,reduce:A.reduce,push:A.push,sort:A.sort,
indexOf:A.indexOf,concat:A.concat,map:function(a){return h(h.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return h(t.apply(this,arguments))},ready:function(a){return X.test(B.readyState)&&B.body?a(h):B.addEventListener("DOMContentLoaded",function(){a(h)},!1),this},get:function(a){return a===n?t.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},
each:function(a){return A.every.call(this,function(b,c){return!1!==a.call(b,c,b)}),this},filter:function(a){return e(a)?this.not(this.not(a)):h(p.call(this,function(b){return v.matches(b,a)}))},add:function(a,b){return h(G(this.concat(h(a,b))))},is:function(a){return 0<this.length&&v.matches(this[0],a)},not:function(a){var b=[];if(e(a)&&a.call!==n)this.each(function(c){a.call(this,c)||b.push(this)});else{var c="string"==typeof a?this.filter(a):"number"==typeof a.length&&e(a.item)?t.call(a):h(a);this.forEach(function(a){0>
c.indexOf(a)&&b.push(a)})}return h(b)},has:function(a){return this.filter(function(){return c(a)?h.contains(this,a):h(this).find(a).size()})},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!c(a)?a:h(a)},last:function(){var a=this[this.length-1];return a&&!c(a)?a:h(a)},find:function(a){var b=this;return"object"==typeof a?h(a).filter(function(){var a=this;return A.some.call(b,function(b){return h.contains(b,a)})}):1==this.length?h(v.qsa(this[0],
a)):this.map(function(){return v.qsa(this,a)})},closest:function(a,b){var c=this[0],e=!1;for("object"==typeof a&&(e=h(a));c&&!(e?0<=e.indexOf(c):v.matches(c,a));)c=c!==b&&!d(c)&&c.parentNode;return h(c)},parents:function(a){for(var b=[],c=this;0<c.length;)c=h.map(c,function(a){return(a=a.parentNode)&&!d(a)&&0>b.indexOf(a)?(b.push(a),a):void 0});return y(b,a)},parent:function(a){return y(G(this.pluck("parentNode")),a)},children:function(a){return y(this.map(function(){return D(this)}),a)},contents:function(){return this.map(function(){return t.call(this.childNodes)})},
siblings:function(a){return y(this.map(function(a,b){return p.call(D(b.parentNode),function(a){return a!==b})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return h.map(this,function(b){return b[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display="");if("none"==getComputedStyle(this,"").getPropertyValue("display")){var a=this.style,b;b=this.nodeName;var c,d;b=(M[b]||(c=B.createElement(b),B.body.appendChild(c),
d=getComputedStyle(c,"").getPropertyValue("display"),c.parentNode.removeChild(c),"none"==d&&(d="block"),M[b]=d),M[b]);a.display=b}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){var b=e(a);if(this[0]&&!b)var c=h(a).get(0),d=c.parentNode||1<this.length;return this.each(function(e){h(this).wrapAll(b?a.call(this,e):d?c.cloneNode(!0):c)})},wrapAll:function(a){if(this[0]){h(this[0]).before(a=h(a));for(var b;(b=a.children()).length;)a=b.first();h(a).append(this)}return this},
wrapInner:function(a){var b=e(a);return this.each(function(c){var d=h(this),e=d.contents();c=b?a.call(this,c):a;e.length?e.wrapAll(c):d.append(c)})},unwrap:function(){return this.parent().each(function(){h(this).replaceWith(h(this).children())}),this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(a){return this.each(function(){var b=h(this);(a===n?"none"==b.css("display"):a)?b.show():b.hide()})},prev:function(a){return h(this.pluck("previousElementSibling")).filter(a||
"*")},next:function(a){return h(this.pluck("nextElementSibling")).filter(a||"*")},html:function(a){return 0===arguments.length?0<this.length?this[0].innerHTML:null:this.each(function(b){var c=this.innerHTML;h(this).empty().append(r(this,a,b,c))})},text:function(a){return 0===arguments.length?0<this.length?this[0].textContent:null:this.each(function(){this.textContent=a===n?"":""+a})},attr:function(a,b){var d;return"string"==typeof a&&b===n?0==this.length||1!==this[0].nodeType?n:"value"==a&&"INPUT"==
this[0].nodeName?this.val():!(d=this[0].getAttribute(a))&&a in this[0]?this[0][a]:d:this.each(function(d){if(1===this.nodeType)if(c(a))for(m in a){d=m;var e=a[m];null==e?this.removeAttribute(d):this.setAttribute(d,e)}else d=r(this,b,d,this.getAttribute(a)),null==d?this.removeAttribute(a):this.setAttribute(a,d)})},removeAttr:function(a){return this.each(function(){1===this.nodeType&&this.removeAttribute(a)})},prop:function(a,b){return a=Z[a]||a,b===n?this[0]&&this[0][a]:this.each(function(c){this[a]=
r(this,b,c,this[a])})},data:function(a,b){var c=this.attr("data-"+a.replace(V,"-$1").toLowerCase(),b);return null!==c?k(c):n},val:function(a){return 0===arguments.length?this[0]&&(this[0].multiple?h(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value):this.each(function(b){this.value=r(this,a,b,this.value)})},offset:function(a){if(a)return this.each(function(b){var c=h(this);b=r(this,a,b,c.offset());var d=c.offsetParent().offset();b={top:b.top-d.top,left:b.left-
d.left};"static"==c.css("position")&&(b.position="relative");c.css(b)});if(0==this.length)return null;var b=this[0].getBoundingClientRect();return{left:b.left+window.pageXOffset,top:b.top+window.pageYOffset,width:Math.round(b.width),height:Math.round(b.height)}},css:function(b,c){if(2>arguments.length){var d=this[0],e=getComputedStyle(d,"");if(!d)return;if("string"==typeof b)return d.style[F(b)]||e.getPropertyValue(b);if(I(b)){var t={};return h.each(I(b)?b:[b],function(a,b){t[b]=d.style[F(b)]||e.getPropertyValue(b)}),
t}}var p="";if("string"==a(b))c||0===c?p=q(b)+":"+w(b,c):this.each(function(){this.style.removeProperty(q(b))});else for(m in b)b[m]||0===b[m]?p+=q(m)+":"+w(m,b[m])+";":this.each(function(){this.style.removeProperty(q(m))});return this.each(function(){this.style.cssText+=";"+p})},index:function(a){return a?this.indexOf(h(a)[0]):this.parent().children().indexOf(this[0])},hasClass:function(a){return a?A.some.call(this,function(a){return this.test(u(a))},E(a)):!1},addClass:function(a){return a?this.each(function(b){x=
[];var c=u(this);r(this,a,b,c).split(/\s+/g).forEach(function(a){h(this).hasClass(a)||x.push(a)},this);x.length&&u(this,c+(c?" ":"")+x.join(" "))}):this},removeClass:function(a){return this.each(function(b){return a===n?u(this,""):(x=u(this),r(this,a,b,x).split(/\s+/g).forEach(function(a){x=x.replace(E(a)," ")}),void u(this,x.trim()))})},toggleClass:function(a,b){return a?this.each(function(c){var d=h(this);r(this,a,c,u(this)).split(/\s+/g).forEach(function(a){(b===n?!d.hasClass(a):b)?d.addClass(a):
d.removeClass(a)})}):this},scrollTop:function(a){if(this.length){var b="scrollTop"in this[0];return a===n?b?this[0].scrollTop:this[0].pageYOffset:this.each(b?function(){this.scrollTop=a}:function(){this.scrollTo(this.scrollX,a)})}},scrollLeft:function(a){if(this.length){var b="scrollLeft"in this[0];return a===n?b?this[0].scrollLeft:this[0].pageXOffset:this.each(b?function(){this.scrollLeft=a}:function(){this.scrollTo(a,this.scrollY)})}},position:function(){if(this.length){var a=this[0],b=this.offsetParent(),
c=this.offset(),d=O.test(b[0].nodeName)?{top:0,left:0}:b.offset();return c.top-=parseFloat(h(a).css("margin-top"))||0,c.left-=parseFloat(h(a).css("margin-left"))||0,d.top+=parseFloat(h(b[0]).css("border-top-width"))||0,d.left+=parseFloat(h(b[0]).css("border-left-width"))||0,{top:c.top-d.top,left:c.left-d.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||B.body;a&&!O.test(a.nodeName)&&"static"==h(a).css("position");)a=a.offsetParent;return a})}},h.fn.detach=h.fn.remove,
["width","height"].forEach(function(a){var c=a.replace(/./,function(a){return a[0].toUpperCase()});h.fn[a]=function(e){var t,p=this[0];return e===n?b(p)?p["inner"+c]:d(p)?p.documentElement["scroll"+c]:(t=this.offset())&&t[a]:this.each(function(b){p=h(this);p.css(a,r(this,e,b,p[a]()))})}}),["after","prepend","before","append"].forEach(function(b,c){var d=c%2;h.fn[b]=function(){var b,e,t=h.map(arguments,function(c){return b=a(c),"object"==b||"array"==b||null==c?c:v.fragment(c)}),p=1<this.length;return 1>
t.length?this:this.each(function(a,b){e=d?b:b.parentNode;b=0==c?b.nextSibling:1==c?b.firstChild:2==c?b:null;t.forEach(function(a){if(p)a=a.cloneNode(!0);else if(!e)return h(a).remove();z(e.insertBefore(a,b),function(a){null==a.nodeName||"SCRIPT"!==a.nodeName.toUpperCase()||a.type&&"text/javascript"!==a.type||a.src||window.eval.call(window,a.innerHTML)})})})};h.fn[d?b+"To":"insert"+(c?"Before":"After")]=function(a){return h(a)[b](this),this}}),v.Z.prototype=h.fn,v.uniq=G,v.deserializeValue=k,h.zepto=
v,h}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(a){function e(a){return a._zid||(a._zid=D++)}function b(a,b,c,f){if(b=d(b),b.ns)var k=new RegExp("(?:^| )"+b.ns.replace(" "," .* ?")+"(?: |$)");return(u[e(a)]||[]).filter(function(a){return!(!a||b.e&&a.e!=b.e||b.ns&&!k.test(a.ns)||c&&e(a.fn)!==e(c)||f&&a.sel!=f)})}function d(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function c(a){return m[a]||z&&n[a]||a}function f(b,t,p,f,k,g,h){var H=e(b),r=u[H]||(u[H]=[]);t.split(/\s/).forEach(function(e){if("ready"==e)return a(document).ready(p);
var t=d(e);t.fn=p;t.sel=k;t.e in m&&(p=function(b){var c=b.relatedTarget;return!c||c!==this&&!a.contains(this,c)?t.fn.apply(this,arguments):void 0});var H=(t.del=g)||p;t.proxy=function(a){if(a=q(a),!a.isImmediatePropagationStopped()){a.data=f;var c=H.apply(b,a._args==w?[a]:[a].concat(a._args));return!1===c&&(a.preventDefault(),a.stopPropagation()),c}};t.i=r.length;r.push(t);"addEventListener"in b&&b.addEventListener(c(t.e),t.proxy,t.del&&!z&&t.e in n||!!h)})}function g(a,d,p,f,k){var g=e(a);(d||"").split(/\s/).forEach(function(d){b(a,
d,p,f).forEach(function(b){delete u[g][b.i];"removeEventListener"in a&&a.removeEventListener(c(b.e),b.proxy,b.del&&!z&&b.e in n||!!k)})})}function q(b,c){return(c||!b.isDefaultPrevented)&&(c||(c=b),a.each(G,function(a,d){var e=c[a];b[a]=function(){return this[d]=h,e&&e.apply(c,arguments)};b[d]=x}),(c.defaultPrevented!==w?c.defaultPrevented:"returnValue"in c?!1===c.returnValue:c.getPreventDefault&&c.getPreventDefault())&&(b.isDefaultPrevented=h)),b}function E(a){var b,c={originalEvent:a};for(b in a)F.test(b)||
a[b]===w||(c[b]=a[b]);return q(c,a)}var w,D=1,C=Array.prototype.slice,y=a.isFunction,r=function(a){return"string"==typeof a},u={},k={},z="onfocusin"in window,n={focus:"focusin",blur:"focusout"},m={mouseenter:"mouseover",mouseleave:"mouseout"};k.click=k.mousedown=k.mouseup=k.mousemove="MouseEvents";a.event={add:f,remove:g};a.proxy=function(b,c){if(y(b)){var d=function(){return b.apply(c,arguments)};return d._zid=e(b),d}if(r(c))return a.proxy(b[c],b);throw new TypeError("expected function");};a.fn.bind=
function(a,b,c){return this.on(a,b,c)};a.fn.unbind=function(a,b){return this.off(a,b)};a.fn.one=function(a,b,c,d){return this.on(a,b,c,d,1)};var h=function(){return!0},x=function(){return!1},F=/^([A-Z]|returnValue$|layer[XY]$)/,G={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};a.fn.delegate=function(a,b,c){return this.on(b,a,c)};a.fn.undelegate=function(a,b,c){return this.off(b,a,c)};a.fn.live=function(b,c){return a(document.body).delegate(this.selector,
b,c),this};a.fn.die=function(b,c){return a(document.body).undelegate(this.selector,b,c),this};a.fn.on=function(b,c,d,e,k){var h,z,n=this;return b&&!r(b)?(a.each(b,function(a,b){n.on(a,c,d,b,k)}),n):(r(c)||y(e)||!1===e||(e=d,d=c,c=w),(y(d)||!1===d)&&(e=d,d=w),!1===e&&(e=x),n.each(function(n,l){k&&(h=function(a){return g(l,a.type,e),e.apply(this,arguments)});c&&(z=function(b){var d,f=a(b.target).closest(c,l).get(0);return f&&f!==l?(d=a.extend(E(b),{currentTarget:f,liveFired:l}),(h||e).apply(f,[d].concat(C.call(arguments,
1)))):void 0});f(l,b,e,d,c,z||h)}))};a.fn.off=function(b,c,d){var e=this;return b&&!r(b)?(a.each(b,function(a,b){e.off(a,c,b)}),e):(r(c)||y(d)||!1===d||(d=c,c=w),!1===d&&(d=x),e.each(function(){g(this,b,d,c)}))};a.fn.trigger=function(b,c){return b=r(b)||a.isPlainObject(b)?a.Event(b):q(b),b._args=c,this.each(function(){"dispatchEvent"in this?this.dispatchEvent(b):a(this).triggerHandler(b,c)})};a.fn.triggerHandler=function(c,d){var e,f;return this.each(function(k,g){e=E(r(c)?a.Event(c):c);e._args=d;
e.target=g;a.each(b(g,c.type||c),function(a,b){return f=b.proxy(e),e.isImmediatePropagationStopped()?!1:void 0})}),f};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(b){a.fn[b]=function(a){return a?this.bind(b,a):this.trigger(b)}});["focus","blur"].forEach(function(b){a.fn[b]=function(a){return a?this.bind(b,a):this.each(function(){try{this[b]()}catch(a){}}),
this}});a.Event=function(a,b){r(a)||(b=a,a=b.type);var c=document.createEvent(k[a]||"Events"),d=!0;if(b)for(var e in b)"bubbles"==e?d=!!b[e]:c[e]=b[e];return c.initEvent(a,d,!0),q(c)}})(Zepto);
(function(a){function e(b,c,d,e){b.global?(b=c||z,d=a.Event(d),e=(a(b).trigger(d,e),!d.isDefaultPrevented())):e=void 0;return e}function b(b){b.global&&0===a.active++&&e(b,null,"ajaxStart")}function d(a,b){var c=b.context;return!1===b.beforeSend.call(c,a,b)||!1===e(b,c,"ajaxBeforeSend",[a,b])?!1:void e(b,c,"ajaxSend",[a,b])}function c(a,b,c,d){var f=c.context;c.success.call(f,a,"success",b);d&&d.resolveWith(f,[a,"success",b]);e(c,f,"ajaxSuccess",[b,c,a]);g("success",b,c)}function f(a,b,c,d,f){var k=
d.context;d.error.call(k,c,b,a);f&&f.rejectWith(k,[c,b,a]);e(d,k,"ajaxError",[c,d,a||b]);g(b,c,d)}function g(b,c,d){var f=d.context;d.complete.call(f,c,b);e(d,f,"ajaxComplete",[c,d]);d.global&&!--a.active&&e(d,null,"ajaxStop")}function q(){}function E(a){return a&&(a=a.split(";",2)[0]),a&&(a==F?"html":a==x?"json":m.test(a)?"script":h.test(a)&&"xml")||"text"}function w(a,b){return""==b?a:(a+"&"+b).replace(/[&?]{1,2}/,"?")}function D(b){b.processData&&b.data&&"string"!=a.type(b.data)&&(b.data=a.param(b.data,
b.traditional));!b.data||b.type&&"GET"!=b.type.toUpperCase()||(b.url=w(b.url,b.data),b.data=void 0)}function C(b,c,d,e){return a.isFunction(c)&&(e=d,d=c,c=void 0),a.isFunction(d)||(e=d,d=void 0),{url:b,data:c,success:d,dataType:e}}function y(b,c,d,e){var f,k=a.isArray(c),g=a.isPlainObject(c);a.each(c,function(c,h){f=a.type(h);e&&(c=d?e:e+"["+(g||"object"==f||"array"==f?c:"")+"]");!e&&k?b.add(h.name,h.value):"array"==f||!d&&"object"==f?y(b,h,d,c):b.add(c,h)})}var r,u,k=0,z=window.document,n=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
m=/^(?:text|application)\/javascript/i,h=/^(?:text|application)\/xml/i,x="application/json",F="text/html",G=/^\s*$/;a.active=0;a.ajaxJSONP=function(b,e){if(!("type"in b))return a.ajax(b);var g,h,n=b.jsonpCallback,q=(a.isFunction(n)?n():n)||"jsonp"+ ++k,m=z.createElement("script"),r=window[q],l=function(b){a(m).triggerHandler("error",b||"abort")},u={abort:l};return e&&e.promise(u),a(m).on("load error",function(d,k){clearTimeout(h);a(m).off().remove();"error"!=d.type&&g?c(g[0],u,b,e):f(null,k||"error",
u,b,e);window[q]=r;g&&a.isFunction(r)&&r(g[0]);r=g=void 0}),!1===d(u,b)?(l("abort"),u):(window[q]=function(){g=arguments},m.src=b.url.replace(/\?(.+)=\?/,"?$1="+q),z.head.appendChild(m),0<b.timeout&&(h=setTimeout(function(){l("timeout")},b.timeout)),u)};a.ajaxSettings={type:"GET",beforeSend:q,success:q,error:q,complete:q,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:x,xml:"application/xml, text/xml",
html:F,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};a.ajax=function(e){var k=a.extend({},e||{}),g=a.Deferred&&a.Deferred();for(r in a.ajaxSettings)void 0===k[r]&&(k[r]=a.ajaxSettings[r]);b(k);k.crossDomain||(k.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(k.url)&&RegExp.$2!=window.location.host);k.url||(k.url=window.location.toString());D(k);!1===k.cache&&(k.url=w(k.url,"_="+Date.now()));var h=k.dataType;e=/\?.+=\?/.test(k.url);if("jsonp"==h||e)return e||(k.url=w(k.url,k.jsonp?
k.jsonp+"=?":!1===k.jsonp?"":"callback=?")),a.ajaxJSONP(k,g);var z;e=k.accepts[h];var n={},m=function(a,b){n[a.toLowerCase()]=[a,b]},x=/^([\w-]+:)\/\//.test(k.url)?RegExp.$1:window.location.protocol,l=k.xhr(),y=l.setRequestHeader;if(g&&g.promise(l),k.crossDomain||m("X-Requested-With","XMLHttpRequest"),m("Accept",e||"*/*"),(e=k.mimeType||e)&&(-1<e.indexOf(",")&&(e=e.split(",",2)[0]),l.overrideMimeType&&l.overrideMimeType(e)),(k.contentType||!1!==k.contentType&&k.data&&"GET"!=k.type.toUpperCase())&&
m("Content-Type",k.contentType||"application/x-www-form-urlencoded"),k.headers)for(u in k.headers)m(u,k.headers[u]);if(l.setRequestHeader=m,l.onreadystatechange=function(){if(4==l.readyState){l.onreadystatechange=q;clearTimeout(z);var b,d=!1;if(200<=l.status&&300>l.status||304==l.status||0==l.status&&"file:"==x){h=h||E(k.mimeType||l.getResponseHeader("content-type"));b=l.responseText;try{"script"==h?(0,eval)(b):"xml"==h?b=l.responseXML:"json"==h&&(b=G.test(b)?null:a.parseJSON(b))}catch(e){d=e}d?f(d,
"parsererror",l,k,g):c(b,l,k,g)}else f(l.statusText||null,l.status?"error":"abort",l,k,g)}},!1===d(l,k))return l.abort(),f(null,"abort",l,k,g),l;if(k.xhrFields)for(u in k.xhrFields)l[u]=k.xhrFields[u];l.open(k.type,k.url,"async"in k?k.async:!0,k.username,k.password);for(u in n)y.apply(l,n[u]);return 0<k.timeout&&(z=setTimeout(function(){l.onreadystatechange=q;l.abort();f(null,"timeout",l,k,g)},k.timeout)),l.send(k.data?k.data:null),l};a.get=function(){return a.ajax(C.apply(null,arguments))};a.post=
function(){var b=C.apply(null,arguments);return b.type="POST",a.ajax(b)};a.getJSON=function(){var b=C.apply(null,arguments);return b.dataType="json",a.ajax(b)};a.fn.load=function(b,c,d){if(!this.length)return this;var e,f=this,k=b.split(/\s/);b=C(b,c,d);var g=b.success;return 1<k.length&&(b.url=k[0],e=k[1]),b.success=function(b){f.html(e?a("<div>").html(b.replace(n,"")).find(e):b);g&&g.apply(f,arguments)},a.ajax(b),this};var A=encodeURIComponent;a.param=function(a,b){var c=[];return c.add=function(a,
b){this.push(A(a)+"="+A(b))},y(c,a,b),c.join("&").replace(/%20/g,"+")}})(Zepto);
(function(a){a.fn.serializeArray=function(){var e,b=[];return a([].slice.call(this.get(0).elements)).each(function(){e=a(this);var d=e.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&!this.disabled&&"submit"!=d&&"reset"!=d&&"button"!=d&&("radio"!=d&&"checkbox"!=d||this.checked)&&b.push({name:e.attr("name"),value:e.val()})}),b};a.fn.serialize=function(){var a=[];return this.serializeArray().forEach(function(b){a.push(encodeURIComponent(b.name)+"="+encodeURIComponent(b.value))}),a.join("&")};
a.fn.submit=function(e){e?this.bind("submit",e):this.length&&(e=a.Event("submit"),this.eq(0).trigger(e),e.isDefaultPrevented()||this.get(0).submit());return this}})(Zepto);(function(a){"__proto__"in{}||a.extend(a.zepto,{Z:function(b,c){return b=b||[],a.extend(b,a.fn),b.selector=c||"",b.__Z=!0,b},isZ:function(b){return"array"===a.type(b)&&"__Z"in b}});try{getComputedStyle(void 0)}catch(e){var b=getComputedStyle;window.getComputedStyle=function(a){try{return b(a)}catch(c){return null}}}})(Zepto);
ContentScript={txn_mode_check_item:"WPB WPE WB WE PB PE FCB FCE PFTB PFTE QB QE QPB QPE DEmr DBmr".split(" "),Hadtxn_mode_check_item:"WPB WPE WB WE PB PE FCB FCE PFTB PFTE QB QE QPB QPE".split(" "),WPTypeCheck_Item:"WPB WPE WB WE PB PE".split(" "),urlX:"http://"+window.location.host,needAjaxCount:[],timerWithOrderClock:null,timerCountPageEatAndBet:null,StaticAllData:[],AlertMsg:"\u8bf7\u8f93\u5165\u5bc6\u7801",AlertPassToLater:"\u8f6f\u4ef6\u8fc7\u671f",PassError:"\u5bc6\u7801\u9519\u8bef",StaticOldAllData:[],
StaticCountShowData:[],StaticOldCountShowData:[],HelloKitty:"81dc9bdb52d04dc20036dbd8313ed055",HelloKittyTime:["fa29e79105dc1fd3e9a7b54d9ae0e2f1","519edc8db508d1c088f793f2c3647e6f"],DaoQiTime:"2015-07-31",PageConfig:{MaxCount:90,Discount:80,LimitStart:700,LimitEnd:700,Percent:1},showCountWithWhere:function(){ContentScript.StaticOldCountShowData=ContentScript.StaticCountShowData;ContentScript.StaticCountShowData=ContentScript.GetAllHadTransactionData();JSON.stringify(ContentScript.StaticOldCountShowData)!=
JSON.stringify(ContentScript.StaticCountShowData)&&ContentScript.showCountPageEatAndBet()},setLimitAndDiscount:function(){var a=$("input[name='orderType']:checked").val();"WP"==a&&($("#MaxCount").val(90),$("#Discount1").val(82),$("#LimitStart1").val(240),$("#LimitEnd1").val(60),$("#Discount2").val(82),$("#LimitStart2").val(240),$("#LimitEnd2").val(60));"QP"==a&&($("#MaxCount").val(90),$("#Discount1").val(80),$("#LimitStart1").val(400),$("#LimitEnd1").val(400),$("#Discount2").val(80),$("#LimitStart2").val(400),
$("#LimitEnd2").val(400));"Q"==a&&($("#MaxCount").val(90),$("#Discount1").val(80),$("#LimitStart1").val(700),$("#LimitEnd1").val(700),$("#Discount2").val(80),$("#LimitStart2").val(700),$("#LimitEnd2").val(700))},showCountPageEatAndBet:function(){var a=[],e=$("input[name='orderType']:checked").val(),b=0,d=0,c=[],f=[];"WP"==e&&(a="WPB WPE WB WE PB PE".split(" "));"QP"==e&&(a="FCB FCE PFTB PFTE QB QE QPB QPE".split(" "));"Q"==e&&(a=["FCB","FCE","QB","QE"]);$(ContentScript.StaticCountShowData).each(function(e){a.contains($(this)[0].type)&&
(0<=$(this)[0].type.indexOf("B")&&!c.contains($(this)[0].id)&&(d++,c.push($(this)[0].id)),0<=$(this)[0].type.indexOf("E")&&!f.contains($(this)[0].id)&&(b++,f.push($(this)[0].id)))});$("#eatCount").text(b);$("#betCount").text(d)},GetAllEatTransactionData:function(){var a=[],e=ContentScript.GetAllTransactionData();$(e).each(function(b){0<=$(this)[0].type.indexOf("E")&&"DEmr"!=$(this)[0].type&&a.push($(this)[0])});return a},GetAllBetTransactionData:function(){var a=[],e=ContentScript.GetAllTransactionData();
$(e).each(function(b){0<=$(this)[0].type.indexOf("B")&&"DBmr"!=$(this)[0].type&&a.push($(this)[0])});return a},GetAllDBmrTransactionData:function(){var a=[],e=ContentScript.GetAllTransactionData();$(e).each(function(b){0<=$(this)[0].type.indexOf("DBmr")&&(b=$(this)[0],0<$(this)[0].t.indexOf("/")&&(b.type="WPB"),0<$(this)[0].fb.indexOf("-")&&(b.type="QB"),a.push(b))});return a},GetAllDEmrTransactionData:function(){var a=[],e=ContentScript.GetAllTransactionData();$(e).each(function(b){0<=$(this)[0].type.indexOf("DEmr")&&
(b=$(this)[0],0<$(this)[0].t.indexOf("/")&&(b.type="WPE"),0<$(this)[0].fb.indexOf("-")&&(b.type="QE"),a.push(b))});return a},Request:function(a){var e=location.href,e=e.substring(e.indexOf("?")+1,e.length).split("&"),b={};for(i=0;j=e[i];i++)b[j.substring(0,j.indexOf("=")).toLowerCase()]=j.substring(j.indexOf("=")+1,j.length);a=b[a.toLowerCase()];return"undefined"==typeof a?"":a},GetSignInInfo:function(){var a="",a=0<=window.location.href.indexOf("ctb988.com")?"com":"net",e=window.location.pathname;
window.location.search.split("?");var b=$("input[name='race_type']").val(),d=$("input[name='race_date']").val(),c=$.trim($("#username").text());return{id:a+e+b+d+c,url:e,loginuser:c,RaceType:b,RaceDate:d,Sml:"s",SiteType:a}},MaxCountEvent:function(){try{ContentScript.PageConfig.MaxCount=$("#MaxCount").val()}catch(a){ContentScript.PageConfig.MaxCount=90,$("#MaxCount").val(90)}var e=$("input[name='DiscountType']:checked").val();try{ContentScript.PageConfig.Discount="F1"==e?$("#Discount1").val():$("#Discount2").val()}catch(b){ContentScript.PageConfig.Discount=
80,$("#Discount").val(80)}try{ContentScript.PageConfig.LimitStart="F1"==e?$("#LimitStart1").val():$("#LimitStart2").val()}catch(d){ContentScript.PageConfig.LimitStart=700,$("#LimitStart").val(700)}try{ContentScript.PageConfig.LimitEnd="F1"==e?$("#LimitEnd1").val():$("#LimitEnd2").val()}catch(c){ContentScript.PageConfig.LimitEnd=700,$("#LimitEnd").val(700)}},onInit:function(){var a=window.location.href;if(0<=a.indexOf("playerhk.jsp")||0<=a.indexOf("Q.jsp")){var a=new Date,e=a.getFullYear()+""+(a.getMonth()+
1);if(localStorage.CheckDate!=a.getFullYear()+""+(a.getMonth()+1)+""+a.getDate()){var b=prompt(ContentScript.AlertMsg,"");ContentScript.HelloKittyTime.contains(MD5Helper.hex_md5(e))?MD5Helper.hex_md5(b)==ContentScript.HelloKitty?(localStorage.CheckDate=a.getFullYear()+""+(a.getMonth()+1)+""+a.getDate(),ContentScript.allOnitEvent()):alert(ContentScript.PassError):alert(ContentScript.AlertPassToLater)}else ContentScript.allOnitEvent()}},allOnitEvent:function(){ContentScript.CreateHtmlElement();ContentScript.HtmlAddDragEvent();
$("#daoqitime").text(ContentScript.DaoQiTime);ContentScript.MaxCountEvent();ContentScript.timerCountPageEatAndBet=self.setInterval(function(){ContentScript.showCountWithWhere()},1E3);$("#btnEnd").hide();$("input[name='orderType']").bind("click",function(){ContentScript.showCountPageEatAndBet();ContentScript.setLimitAndDiscount()});$("#btnEatDelete").bind("click",function(){$(this).hide();var a=$(window.frames.frmTRANS.document).find(".del2_ch");null!=a&&void 0!=a&&$(window.frames.frmTRANS.document).find(".del2_ch").last().click();
$(this).show()});$("#btnBetDelete").bind("click",function(){$(this).hide();var a=$(window.frames.frmTRANS.document).find(".del_ch");null!=a&&void 0!=a&&$(window.frames.frmTRANS.document).find(".del_ch").last().click();$(this).show()});$("#btnStart").bind("click",function(){ContentScript.StaticOldAllData=[];ContentScript.StaticAllData=[];$("#btnStart").hide();$("#btnEnd").show();ContentScript.MaxCountEvent();ContentScript.timerWithOrderClock=self.setInterval(function(){clearInterval(ContentScript.timerCountPageEatAndBet);
ContentScript.StaticOldAllData=ContentScript.StaticAllData;ContentScript.StaticAllData=ContentScript.GetAllHadTransactionData();JSON.stringify(ContentScript.StaticOldAllData)!=JSON.stringify(ContentScript.StaticAllData)&&(ContentScript.StaticCountShowData=ContentScript.StaticAllData,ContentScript.showCountPageEatAndBet(),ContentScript.needAjaxCount=ContentScript.getNeedWithOrderList(),ContentScript.withOrderOnInit(ContentScript.needAjaxCount,!1))},1E3)});$("#btnEnd").bind("click",function(){null!=
ContentScript.timerWithOrderClock&&clearInterval(ContentScript.timerWithOrderClock);ContentScript.timerWithOrderClock=null;ContentScript.timerCountPageEatAndBet=self.setInterval(function(){ContentScript.showCountWithWhere()},1E3);$("#btnStart").show();$("#btnEnd").hide()});$("#btnBanlance").bind("click",function(){null==ContentScript.timerWithOrderClock?($(this).hide(),setTimeout(function(){ContentScript.EatButtonEvent()},0),setTimeout(function(){ContentScript.BetButtonEvent()},0),setTimeout(function(){ContentScript.withOrderOnInit(ContentScript.getNeedPingCangOrderList(),
!0)},1E3),$(this).show()):alert("\u8bf7\u5148\u505c\u6b62\u8ddf\u5355\uff01")})},getNeedWithOrderList:function(){var a=$("input[name='orderType']:checked").val(),e=[],b=[],d=[];if(0<a.length){"WP"==a&&(d="WPB WPE WB WE PB PE".split(" "));"QP"==a&&(d="FCB FCE PFTB PFTE QB QE QPB QPE".split(" "));"Q"==a&&(d=["FCB","FCE","QB","QE"]);var c=ContentScript.GetAllTransactionData(),f=[],e=[];if("WP"==a){var g=[],q=[],E=[],w=[],D=[],C=[];$(c).each(function(a){a=$(this)[0];"DBmr"==$(this)[0].type&&(0<parseInt($(this)[0].fb)&&
0<parseInt($(this)[0].x)&&(a.type="WPB",a.id=a.matches+a.rdfb,a.fb=-1*parseInt(a.fb),a.x=-1*parseInt(a.x),g.push(a)),0==parseInt($(this)[0].fb)&&0<parseInt($(this)[0].x)&&(a.type="PB",a.id=a.matches+a.rdfb,a.fb=-1*parseInt(a.fb),a.x=-1*parseInt(a.x),D.push(a)),0<parseInt($(this)[0].fb)&&0==parseInt($(this)[0].x)&&(a.type="WB",a.id=a.matches+a.rdfb,a.fb=-1*parseInt(a.fb),a.x=-1*parseInt(a.x),D.push(a)));if(d.contains($(this)[0].type))switch(a=$(this)[0],$(this)[0].type){case "WPB":a.id=a.matches+a.rdfb;
a.fb=-1*parseInt(a.fb);a.x=-1*parseInt(a.x);g.push(a);break;case "WPE":a.id=a.matches+a.rdfb;a.fb=1*parseInt(a.fb);a.x=1*parseInt(a.x);q.push(a);break;case "WB":a.id=a.matches+a.rdfb;a.fb=-1*parseInt(a.fb);a.x=-1*parseInt(a.x);E.push(a);break;case "WE":a.id=a.matches+a.rdfb;a.fb=1*parseInt(a.fb);a.x=1*parseInt(a.x);w.push(a);break;case "PE":a.id=a.matches+a.rdfb;a.fb=1*parseInt(a.fb);a.x=1*parseInt(a.x);C.push(a);break;case "PB":a.id=a.matches+a.rdfb,a.fb=-1*parseInt(a.fb),a.x=-1*parseInt(a.x),D.push(a)}});
var y=[],r=[],u=[];$(q).each(function(a){var b=$(this)[0],c=!1;$(y).each(function(a){b.id==$(this)[0].id&&($(this)[0].x=parseInt($(this)[0].x)+parseInt(b.x),$(this)[0].fb=parseInt($(this)[0].fb)+parseInt(b.fb),c=!0)});c||y.push(q[a])});$(C).each(function(a){var b=$(this)[0],c=!1;$(u).each(function(a){b.id==$(this)[0].id&&($(this)[0].x=parseInt($(this)[0].x)+parseInt(b.x),$(this)[0].fb=parseInt($(this)[0].fb)+parseInt(b.fb),c=!0)});c||u.push(C[a])});$(w).each(function(a){var b=$(this)[0],c=!1;$(r).each(function(a){b.id==
$(this)[0].id&&($(this)[0].x=parseInt($(this)[0].x)+parseInt(b.x),$(this)[0].fb=parseInt($(this)[0].fb)+parseInt(b.fb),c=!0)});c||r.push(w[a])});$(q).each(function(a){var c=$(this)[0];$(g).each(function(a){c.id==$(this)[0].id&&(c.fb=parseInt(c.fb)+parseInt($(this)[0].fb),c.x=parseInt(c.x)+parseInt($(this)[0].x))});0<c.fb&&0<c.x&&b.push(c)});$(w).each(function(a){var c=$(this)[0];$(E).each(function(a){c.id==$(this)[0].id&&(c.fb=parseInt(c.fb)+parseInt($(this)[0].fb),c.x=parseInt(c.x)+parseInt($(this)[0].x))});
0<c.fb&&0==c.x&&b.push(c)});$(C).each(function(a){var c=$(this)[0];$(D).each(function(a){c.id==$(this)[0].id&&(c.fb=parseInt(c.fb)+parseInt($(this)[0].fb),c.x=parseInt(c.x)+parseInt($(this)[0].x))});0==c.fb&&0<c.x&&b.push(c)});$(b).each(function(a){$(this)[0].type=$(this)[0].type.replace("E","B")});return b}$(c).each(function(a){if(d.contains($(this)[0].type)&&"DEmr"!=$(this)[0].type&&"DBmr"!=$(this)[0].type){if(0<=$(this)[0].type.indexOf("E")){var b=$(this)[0],g=!1;$(e).each(function(a){b.id==$(this)[0].id&&
($(this)[0].x=parseInt($(this)[0].x)+parseInt(b.x),g=!0)});g||(c[a].x=parseInt(c[a].x),e.push(c[a]))}0<=$(this)[0].type.indexOf("B")&&(b=$(this)[0],g=!1,$(e).each(function(a){b.id==$(this)[0].id&&($(this)[0].x=parseInt($(this)[0].x)+-1*parseInt(b.x),g=!0)}),g||(c[a].x=-1*parseInt(c[a].x),e.push(c[a])))}"DBmr"==$(this)[0].type&&(b=$(this)[0],g=!1,$(f).each(function(a){b.id==$(this)[0].id&&($(this)[0].x=parseInt($(this)[0].x)+parseInt(b.x),g=!0)}),g||f.push(c[a]))});$(e).each(function(a){var b=$(this)[0];
$(f).each(function(){b.id==$(this)[0].id&&(e[a].x-=$(this)[0].x)})});$(e).each(function(a){a=$(this)[0];0<a.x&&b.push(a)});$(b).each(function(a){$(this)[0].type=$(this)[0].type.replace("E","B")});return b}return[]},getNeedPingCangOrderList:function(){var a=$("input[name='orderType']:checked").val(),e=[],b=[],d=[];if(0<a.length){"WP"==a&&(d="WPB WPE WB WE PB PE".split(" "));"QP"==a&&(d="FCB FCE PFTB PFTE QB QE QPB QPE".split(" "));"Q"==a&&(d=["FCB","FCE","QB","QE"]);var c=ContentScript.GetAllHadTransactionData(),
e=[];$(c).each(function(a){if(d.contains($(this)[0].type)&&"DEmr"!=$(this)[0].type&&"DBmr"!=$(this)[0].type){if(0<=$(this)[0].type.indexOf("E")){var b=$(this)[0],q=!1;$(e).each(function(a){b.id==$(this)[0].id&&($(this)[0].x=parseInt($(this)[0].x)+parseInt(b.x),q=!0)});q||(c[a].x=parseInt(c[a].x),e.push(c[a]))}0<=$(this)[0].type.indexOf("B")&&(b=$(this)[0],q=!1,$(e).each(function(a){b.id==$(this)[0].id&&($(this)[0].x=parseInt($(this)[0].x)+-1*parseInt(b.x),q=!0)}),q||(c[a].x=-1*parseInt(c[a].x),e.push(c[a])))}});
$(e).each(function(a){a=$(this)[0];0<a.x&&b.push(a)});$(b).each(function(a){$(this)[0].type=$(this)[0].type.replace("E","B")});return b}return[]},ticketByFloat:function(a,e){return a},withOrderOnInit:function(a,e){$(a).each(function(a){a=$(this)[0];var d=ContentScript.GetSignInInfo();if("FCB FCE PFTB PFTE QB QE QPB QPE".split(" ").contains(a.type)){var c={task:"betBox",combo:0};c.Tix=ContentScript.ticketByFloat(parseInt(a.x),"Q");c.Race=parseInt(a.matches);var f,g;0>a.fb.indexOf("(")?(f=a.fb.split("-")[0],
g=a.fb.split("-")[1],c.fctype=0):(f=a.fb.replace(/\(/g,"").replace(/\)/g,"").split("-")[0],g=a.fb.replace(/\(/g,"").replace(/\)/g,"").split("-")[1],c.fctype=1);c.Hs1=f;c.Hs2=g;c.Hs3="";c.Hs4="";c.Hs5="";c.Hs6="";c.Hs7="";c.Hs8="";c.Q="Q";0<=a.type.indexOf("E")?c.type="EAT":c.type="BET";c.amount=e?100:ContentScript.PageConfig.Discount;c.fclmt=ContentScript.PageConfig.LimitStart;c.overflow="1";c.race_type=d.RaceType;c.race_date=d.RaceDate;c.show=parseInt(a.matches);c.rd=Math.random();console.log(c);
$.ajax({type:"get",url:ContentScript.urlX+"/forecast",data:c,success:function(a){console.log(a)},error:function(a){console.log(a)}})}"WPB WPE WB WE PB PE".split(" ").contains($(this)[0].type)&&(f="",c={t:"frm"},c.race=a.matches,c.horse=a.rdfb,c.win=ContentScript.ticketByFloat(parseInt(a.fb),"WP"),c.place=a.x,f="",0<=a.type.indexOf("E")?(c.type="eat",f="/bets"):(c.type="bet",f="/bookings"),c.amount=e?100:ContentScript.PageConfig.Discount,c.limit=ContentScript.PageConfig.LimitStart+"/"+ContentScript.PageConfig.LimitEnd,
c.race_type=d.RaceType,c.race_date=d.RaceDate,c.show=parseInt(a.matches),c.post="1",c.rd=Math.random(),console.log(c),$.ajax({type:"get",url:ContentScript.urlX+f,data:c,success:function(a){console.log(a)},error:function(a){console.log(a)}}))})},GetAllTransactionData:function(){var a=[];$(ContentScript.txn_mode_check_item).each(function(e){var b=ContentScript.txn_mode_check_item[e];$(window.frames.frmTRANS.document).find("tbody[id^='"+b+"'] tr").each(function(){var d="";$(this).find("td").each(function(a){d+=
$(this).text()+"$"});if(0<d.length){var c=d.split("$");item={id:c[0]+c[1]+c[2],type:b,matches:c[0],rdfb:c[1],fb:c[2],x:c[3],y:c[4],t:c[5]};a.push(item)}})});return a},GetAllHadTransactionData:function(){var a=[];$(ContentScript.Hadtxn_mode_check_item).each(function(e){var b=ContentScript.txn_mode_check_item[e];$(window.frames.frmTRANS.document).find("tbody[id^='"+b+"'] tr").each(function(){var d="";$(this).find("td").each(function(a){d+=$(this).text()+"$"});if(0<d.length){var c=d.split("$");item=
{id:c[0]+c[1]+c[2],type:b,matches:c[0],rdfb:c[1],fb:c[2],x:c[3],y:c[4],t:c[5]};a.push(item)}})});return a},CreateHtmlElement:function(){var a;a='<div id="drag" style="background:white;width: 330px; height: 180px; position: absolute; border: solid 1px #ccc; float: right; z-index: 100;right: 0;top: 0;min-height: 180px;overflow-y: auto;max-height: 600px;">'+('<h3 style="color: #fff; background: none repeat scroll 0 0 rgba(16, 90, 31, 0.7); color: #FFFFFF; height: 30px; line-height: 30px; margin: 0;">\u5f53\u524d\u8d26\u6237:'+
$.trim($("#username").text())+' &nbsp; \u5230\u671f\u65f6\u95f4<span id="daoqitime"></span></h3>');a+='<table style="width:100%"><tr style="line-height: 30px;"><td colspan="2">';a+='<input type= "radio" name="orderType"  value="Q" checked="checked" id="QType"/>Q';a+='<input type= "radio" name="orderType"  value="WP" id="WPType"/>WP';a+='<input type= "radio" name="orderType"  value="QP" id="QPType"/>QP';a+='&nbsp;&nbsp;\u9650\u6ce8:<input id="MaxCount" type="number" step="1" style="width: 40px;" size="4" value="90" />';
a+="</td></tr>";a+='<tr style="line-height: 30px;" ><td colspan="2">';a+='<input type= "radio" name="DiscountType"  value="F1" checked="checked" id="DiscountType1"/>';a+='\u6298\u5934:<input id="Discount1" type="number" step="10" style="width: 40px;" size="4" value="80" />';a+='\u6781\u9650:<input id="LimitStart1" type="number" step="10" style="width: 40px;" size="4" value="700" />';a+='/<input id="LimitEnd1" type="number" step="10" style="width: 40px;" size="4" value="700" />';a+="</td>";a+="</tr>";
a+='<tr style="line-height: 30px;" ><td colspan="2">';a+='<input type= "radio" name="DiscountType" value="F2" id="DiscountType2"/>';a+='\u6298\u5934:<input id="Discount2" type="number" step="10" style="width: 40px;" size="4" value="80" />';a+='\u6781\u9650:<input id="LimitStart2" type="number" step="10" style="width: 40px;" size="4" value="700" />';a+='/<input id="LimitEnd2" type="number" step="10" style="width: 40px;" size="4" value="700" />';a+="</td>";a+="</tr>";a+='<tr style="line-height: 40px;"><td style="text-align:left;font-size:18px">';
a+='\u5403:<span id="eatCount" style="color:red"></span>&nbsp;\u8d4c:<span id="betCount" style="color:red" ></span>&nbsp;';a+='</td><td style="text-align:right">';a+='<input type="button" id="btnStart" value="\u5f00\u59cb" />';a+='<input type="button" id="btnEnd" value="\u505c\u6b62" />';a+='<input type="button" id="btnBanlance" value="\u5e73\u4ed3" />';a+='<input type="button" id="btnEatDelete" value="\u5220\u5403\u5355" />';a+='<input type="button" id="btnBetDelete" value="\u5220\u8d4c\u5355" />';
a+="</td></tr>";a+="</table>";a+="</div>";$("body").append(a)},EatButtonEvent:function(){var a=$(window.frames.frmTRANS.document).find("tbody[id^='DEmr'] tr");null!=a&&void 0!=a&&0<a.length&&$(window.frames.frmTRANS.document).find("tbody[id^='DEmr'] tr").each(function(a){a=$($(this).find(".del2_ch").parent().parent()).attr("onclick").replace(/mr\(\'/g,"").replace(/\'\)/g,"");PostHelp.AjaxDeleteData(a);$($(this).find(".del2_ch").parent().parent()).hide()})},BetButtonEvent:function(){var a=$(window.frames.frmTRANS.document).find("tbody[id^='DBmr'] tr");
null!=a&&void 0!=a&&0<a.length&&$(window.frames.frmTRANS.document).find("tbody[id^='DBmr'] tr").each(function(a){a=$($(this).find(".del_ch").parent().parent()).attr("onclick").replace(/mr\(\'/g,"").replace(/\'\)/g,"");PostHelp.AjaxDeleteData(a);$($(this).find(".del_ch").parent().parent()).hide()})},HtmlAddDragEvent:function(){var a=!1,e,b;$("#drag").click(function(){}).mousedown(function(d){a=!0;e=d.pageX-parseInt($("#drag").css("left"));b=d.pageY-parseInt($("#drag").css("top"))});$(document).mousemove(function(d){if(a){var c=
d.pageX-e;d=d.pageY-b;$("#drag").css({top:d,left:c})}}).mouseup(function(){a=!1})}};
PostHelp={urlX:"http://"+window.location.host,fcfrm1:$("#fcfrm1"),fcfrm2:$("#fcfrm2"),chkKBBet:function(a){a=PostHelp.fcfrm1;"0"==a.find("input[name='fctype']").val()?PostHelp.chkKB1(a):"1"==a.find("input[name='fctype']").val()&&PostHelp.chkKB3(a)},chkKBEat:function(a){a=PostHelp.fcfrm2;"0"==a.find("input[name='fctype']").val()?PostHelp.chkKB2(a):"1"==a.find("input[name='fctype']").val()&&PostHelp.chkKB4(a)},chkKB1:function(a){a=PostHelp.fcfrm1;var e;e="";null!=a.find("input[name='Hss']")&&void 0!=
a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']").val()&&(e=a.find("input[name='Hss']").val());e=-1<e.indexOf(">")?1:0;var b="";null!=a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']").val()&&0<a.find("input[name='Hss']").val().length&&(b=a.find("input[name='Hss']").val().replace(/\+/g,"_"));""==b&&(b=a.find("input[name='Hs1']").val()+"_"+a.find("input[name='Hs2']").val());PostHelp.postData(PostHelp.urlX+"/forecast?task=betBox&combo="+
e+"&Tix="+a.find("input[name='Tix']").val()+"&Race="+a.find("input[name='Race']").val()+"&Hss="+b+"&fctype="+a.find("input[name='fctype']").val()+"&Q="+a.find("input[name='Q']").val()+"&type="+a.find("input[name='type']").val()+"&overflow="+a.find("input[name='overflow']").val()+"&amount="+a.find("input[name='amount']").val()+"&fclmt="+a.find("input[name='fclmt']").val()+"&race_type="+a.find("input[name='race_type']").val()+"&race_date="+a.find("input[name='race_date']").val())},chkKB2:function(a){a=
PostHelp.fcfrm2;var e=a.find("input[name='banker2']").val(),b="";a.find("input[name='Hss']")&&0<a.find("input[name='Hss']").val().length&&(b=a.find("input[name='Hss']").val().replace(/\+/g,"_"));""==b&&(b=a.find("input[name='Hs1']").val()+"_"+a.find("input[name='Hs2']").val());PostHelp.postData(PostHelp.urlX+"/forecast?task=betBox&combo="+e+"&Tix="+a.find("input[name='Tix']").val()+"&Race="+a.find("input[name='Race']").val()+"&Hss="+b+"&fctype="+a.find("input[name='fctype']").val()+"&Q="+a.find("input[name='Q']").val()+
"&type="+a.find("input[name='type']").val()+"&overflow="+a.find("input[name='overflow']").val()+"&amount="+a.find("input[name='amount']").val()+"&fclmt="+a.find("input[name='fclmt']").val()+"&race_type="+a.find("input[name='race_type']").val()+"&race_date="+a.find("input[name='race_date']").val())},chkKB3:function(a){a=PostHelp.fcfrm1;var e;e="";null!=a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']").val()&&(e=a.find("input[name='Hss']").val());
e=-1<e.indexOf(">")?1:0;var b="";null!=a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']").val()&&""!=a.find("input[name='Hss']").val()&&(b=a.find("input[name='Hss']").val().replace(/\+/g,"_"));""==b&&(b=a.find("input[name='Hs1']").val()+"_"+a.find("input[name='Hs2']").val());PostHelp.postData(PostHelp.urlX+"/forecast?task=betBox&combo="+e+"&Tix="+a.find("input[name='Tix']").val()+"&Race="+a.find("input[name='Race']").val()+"&Hss="+b+"&fctype="+a.find("input[name='fctype']").val()+
"&Q="+a.find("input[name='Q']").val()+"&type="+a.find("input[name='type']").val()+"&overflow="+a.find("input[name='overflow']").val()+"&amount="+a.find("input[name='amount']").val()+"&fclmt="+a.find("input[name='fclmt']").val()+"&race_type="+a.find("input[name='race_type']").val()+"&race_date="+a.find("input[name='race_date']").val())},chkKB4:function(a){a=PostHelp.fcfrm2;var e=a.find("input[name='banker2']").val();a.Order.disabled=!0;var b="";null!=a.find("input[name='Hss']")&&void 0!=a.find("input[name='Hss']")&&
""!=a.find("input[name='Hss']").val()&&(b=a.find("input[name='Hss']").val().replace(/\+/g,"_"));""==b&&(b=a.find("input[name='Hs1']").val()+"_"+a.find("input[name='Hs2']").val());PostHelp.postData(PostHelp.urlX+"/forecast?task=betBox&combo="+e+"&Tix="+a.find("input[name='Tix']").val()+"&Race="+a.find("input[name='Race']").val()+"&Hss="+b+"&fctype="+a.find("input[name='fctype']").val()+"&Q="+a.find("input[name='Q']").val()+"&type="+a.find("input[name='type']").val()+"&overflow="+a.find("input[name='overflow']").val()+
"&amount="+a.find("input[name='amount']").val()+"&fclmt="+a.find("input[name='fclmt']").val()+"&race_type="+a.find("input[name='race_type']").val()+"&race_date="+a.find("input[name='race_date']").val())},chkActBet:function(a){a=PostHelp.fcfrm1;var e;e=a.find("input[name='banker1'] :checked")?1:0;PostHelp.postData(PostHelp.urlX+"/forecast?task=betBox&combo="+e+"&Tix="+a.find("input[name='Tix']").val()+"&Race="+a.find("input[name='Race']").val()+"&Hs1="+a.find("input[name='Hs1']").val()+"&Hs2="+a.find("input[name='Hs2']").val()+
"&Hs3="+a.find("input[name='Hs3']").val()+"&Hs4="+a.find("input[name='Hs4']").val()+"&Hs5="+a.find("input[name='Hs5']").val()+"&Hs6="+a.find("input[name='Hs6']").val()+"&Hs7="+a.find("input[name='Hs7']").val()+"&Hs8="+a.find("input[name='Hs8']").val()+"&fctype="+a.find("input[name='fctype']").val()+"&Q="+a.find("input[name='Q']").val()+"&type="+a.find("input[name='type']").val()+"&overflow="+a.find("input[name='overflow']").val()+"&amount="+a.find("input[name='amount']").val()+"&fclmt="+a.find("input[name='fclmt']").val()+
"&race_type="+a.find("input[name='race_type']").val()+"&race_date="+a.find("input[name='race_date']").val())},chkActEat:function(a){a=PostHelp.fcfrm2;var e=a.find("input[name='banker2']").val();PostHelp.postData(PostHelp.urlX+"/forecast?task=betBox&combo="+e+"&Tix="+a.find("input[name='Tix']").val()+"&Race="+a.find("input[name='Race']").val()+"&Hs1="+a.find("input[name='Hs1']").val()+"&Hs2="+a.find("input[name='Hs2']").val()+"&Hs3="+a.find("input[name='Hs3']").val()+"&Hs4="+a.find("input[name='Hs4']").val()+
"&Hs5="+a.find("input[name='Hs5']").val()+"&Hs6="+a.find("input[name='Hs6']").val()+"&Hs7="+a.find("input[name='Hs7']").val()+"&Hs8="+a.find("input[name='Hs8']").val()+"&fctype="+a.find("input[name='fctype']").val()+"&Q="+a.find("input[name='Q']").val()+"&type="+a.find("input[name='type']").val()+"&overflow="+a.find("input[name='overflow']").val()+"&amount="+a.find("input[name='amount']").val()+"&fclmt="+a.find("input[name='fclmt']").val()+"&race_type="+a.find("input[name='race_type']").val()+"&race_date="+
a.find("input[name='race_date']").val())},postData:function(a){if($("#view1")){var e=$("#view1").val(),e=(a+"&show="+e+"&rd="+Math.random()).split("?");a=e[0];for(var e=e[1].split("&"),b="{",d=0;d<e.length;d++)var c=e[d].split("="),b=b+('"'+c[0]+'": "'+c[1]+'",');b=b.substr(0,b.length-1);e=$.parseJSON(b+"}");$.ajax({type:"GET",url:a,data:e,dataType:"text",success:function(a){},error:function(a,b,c){}})}},PostDeleteData:function(a){var e,b,d,c,f;f=a.split(",");a=f[0];e=f[1];b=f[2];d=f[3];c=f[4];f=
f[5];document.getElementById("boxFcBET").style.display="none";document.getElementById("boxFcEAT").style.display="none";document.getElementById("boxPfcBET").style.display="none";document.getElementById("boxPfcEAT").style.display="none";PostHelp.postData(PostHelp.urlX+"/transactions?type=del&bid="+a+"&x="+e+"&betType="+b+"&race_date="+d+"&race_type="+c+"&q=q&race="+f)},AjaxDeleteData:function(a){a=a.split(",");var e=0;try{e=view1.options[view1.selectedIndex].value}catch(b){e=$(".dd-selected-value").val()}$.ajax({type:"GET",
url:PostHelp.urlX+"/transactions",data:{type:"del",bid:a[0],x:a[1],betType:a[2],race_date:a[3],race_type:a[4],q:"q",race:a[5],show:e,rd:Math.random()},dataType:"text",success:function(a){},error:function(a,b,e){}})}};
MD5Helper={hexcase:0,b64pad:"",chrsz:8,hex_md5:function(a){return MD5Helper.binl2hex(MD5Helper.core_md5(MD5Helper.str2binl(a),a.length*MD5Helper.chrsz))},b64_md5:function(a){return MD5Helper.binl2b64(MD5Helper.core_md5(MD5Helper.str2binl(a),a.length*MD5Helper.chrsz))},str_md5:function(a){return MD5Helper.binl2str(MD5Helper.core_md5(MD5Helper.str2binl(a),a.length*MD5Helper.chrsz))},hex_hmac_md5:function(a,e){return MD5Helper.binl2hex(MD5Helper.core_hmac_md5(a,e))},b64_hmac_md5:function(a,e){return MD5Helper.binl2b64(MD5Helper.core_hmac_md5(a,
e))},str_hmac_md5:function(a,e){return MD5Helper.binl2str(MD5Helper.core_hmac_md5(a,e))},core_md5:function(a,e){a[e>>5]|=128<<e%32;a[(e+64>>>9<<4)+14]=e;for(var b=1732584193,d=-271733879,c=-1732584194,f=271733878,g=0;g<a.length;g+=16)var q=b,E=d,w=c,D=f,b=MD5Helper.md5_ff(b,d,c,f,a[g+0],7,-680876936),f=MD5Helper.md5_ff(f,b,d,c,a[g+1],12,-389564586),c=MD5Helper.md5_ff(c,f,b,d,a[g+2],17,606105819),d=MD5Helper.md5_ff(d,c,f,b,a[g+3],22,-1044525330),b=MD5Helper.md5_ff(b,d,c,f,a[g+4],7,-176418897),f=MD5Helper.md5_ff(f,
b,d,c,a[g+5],12,1200080426),c=MD5Helper.md5_ff(c,f,b,d,a[g+6],17,-1473231341),d=MD5Helper.md5_ff(d,c,f,b,a[g+7],22,-45705983),b=MD5Helper.md5_ff(b,d,c,f,a[g+8],7,1770035416),f=MD5Helper.md5_ff(f,b,d,c,a[g+9],12,-1958414417),c=MD5Helper.md5_ff(c,f,b,d,a[g+10],17,-42063),d=MD5Helper.md5_ff(d,c,f,b,a[g+11],22,-1990404162),b=MD5Helper.md5_ff(b,d,c,f,a[g+12],7,1804603682),f=MD5Helper.md5_ff(f,b,d,c,a[g+13],12,-40341101),c=MD5Helper.md5_ff(c,f,b,d,a[g+14],17,-1502002290),d=MD5Helper.md5_ff(d,c,f,b,a[g+
15],22,1236535329),b=MD5Helper.md5_gg(b,d,c,f,a[g+1],5,-165796510),f=MD5Helper.md5_gg(f,b,d,c,a[g+6],9,-1069501632),c=MD5Helper.md5_gg(c,f,b,d,a[g+11],14,643717713),d=MD5Helper.md5_gg(d,c,f,b,a[g+0],20,-373897302),b=MD5Helper.md5_gg(b,d,c,f,a[g+5],5,-701558691),f=MD5Helper.md5_gg(f,b,d,c,a[g+10],9,38016083),c=MD5Helper.md5_gg(c,f,b,d,a[g+15],14,-660478335),d=MD5Helper.md5_gg(d,c,f,b,a[g+4],20,-405537848),b=MD5Helper.md5_gg(b,d,c,f,a[g+9],5,568446438),f=MD5Helper.md5_gg(f,b,d,c,a[g+14],9,-1019803690),
c=MD5Helper.md5_gg(c,f,b,d,a[g+3],14,-187363961),d=MD5Helper.md5_gg(d,c,f,b,a[g+8],20,1163531501),b=MD5Helper.md5_gg(b,d,c,f,a[g+13],5,-1444681467),f=MD5Helper.md5_gg(f,b,d,c,a[g+2],9,-51403784),c=MD5Helper.md5_gg(c,f,b,d,a[g+7],14,1735328473),d=MD5Helper.md5_gg(d,c,f,b,a[g+12],20,-1926607734),b=MD5Helper.md5_hh(b,d,c,f,a[g+5],4,-378558),f=MD5Helper.md5_hh(f,b,d,c,a[g+8],11,-2022574463),c=MD5Helper.md5_hh(c,f,b,d,a[g+11],16,1839030562),d=MD5Helper.md5_hh(d,c,f,b,a[g+14],23,-35309556),b=MD5Helper.md5_hh(b,
d,c,f,a[g+1],4,-1530992060),f=MD5Helper.md5_hh(f,b,d,c,a[g+4],11,1272893353),c=MD5Helper.md5_hh(c,f,b,d,a[g+7],16,-155497632),d=MD5Helper.md5_hh(d,c,f,b,a[g+10],23,-1094730640),b=MD5Helper.md5_hh(b,d,c,f,a[g+13],4,681279174),f=MD5Helper.md5_hh(f,b,d,c,a[g+0],11,-358537222),c=MD5Helper.md5_hh(c,f,b,d,a[g+3],16,-722521979),d=MD5Helper.md5_hh(d,c,f,b,a[g+6],23,76029189),b=MD5Helper.md5_hh(b,d,c,f,a[g+9],4,-640364487),f=MD5Helper.md5_hh(f,b,d,c,a[g+12],11,-421815835),c=MD5Helper.md5_hh(c,f,b,d,a[g+15],
16,530742520),d=MD5Helper.md5_hh(d,c,f,b,a[g+2],23,-995338651),b=MD5Helper.md5_ii(b,d,c,f,a[g+0],6,-198630844),f=MD5Helper.md5_ii(f,b,d,c,a[g+7],10,1126891415),c=MD5Helper.md5_ii(c,f,b,d,a[g+14],15,-1416354905),d=MD5Helper.md5_ii(d,c,f,b,a[g+5],21,-57434055),b=MD5Helper.md5_ii(b,d,c,f,a[g+12],6,1700485571),f=MD5Helper.md5_ii(f,b,d,c,a[g+3],10,-1894986606),c=MD5Helper.md5_ii(c,f,b,d,a[g+10],15,-1051523),d=MD5Helper.md5_ii(d,c,f,b,a[g+1],21,-2054922799),b=MD5Helper.md5_ii(b,d,c,f,a[g+8],6,1873313359),
f=MD5Helper.md5_ii(f,b,d,c,a[g+15],10,-30611744),c=MD5Helper.md5_ii(c,f,b,d,a[g+6],15,-1560198380),d=MD5Helper.md5_ii(d,c,f,b,a[g+13],21,1309151649),b=MD5Helper.md5_ii(b,d,c,f,a[g+4],6,-145523070),f=MD5Helper.md5_ii(f,b,d,c,a[g+11],10,-1120210379),c=MD5Helper.md5_ii(c,f,b,d,a[g+2],15,718787259),d=MD5Helper.md5_ii(d,c,f,b,a[g+9],21,-343485551),b=MD5Helper.safe_add(b,q),d=MD5Helper.safe_add(d,E),c=MD5Helper.safe_add(c,w),f=MD5Helper.safe_add(f,D);return[b,d,c,f]},md5_cmn:function(a,e,b,d,c,f){return MD5Helper.safe_add(MD5Helper.bit_rol(MD5Helper.safe_add(MD5Helper.safe_add(e,
a),MD5Helper.safe_add(d,f)),c),b)},md5_ff:function(a,e,b,d,c,f,g){return MD5Helper.md5_cmn(e&b|~e&d,a,e,c,f,g)},md5_gg:function(a,e,b,d,c,f,g){return MD5Helper.md5_cmn(e&d|b&~d,a,e,c,f,g)},md5_hh:function(a,e,b,d,c,f,g){return MD5Helper.md5_cmn(e^b^d,a,e,c,f,g)},md5_ii:function(a,e,b,d,c,f,g){return MD5Helper.md5_cmn(b^(e|~d),a,e,c,f,g)},core_hmac_md5:function(a,e){var b=MD5Helper.str2binl(a);16<b.length&&(b=MD5Helper.core_md5(b,a.length*MD5Helper.chrsz));for(var d=Array(16),c=Array(16),f=0;16>f;f++)d[f]=
b[f]^909522486,c[f]=b[f]^1549556828;b=MD5Helper.core_md5(d.concat(MD5Helper.str2binl(e)),512+e.length*MD5Helper.chrsz);return MD5Helper.core_md5(c.concat(b),640)},safe_add:function(a,e){var b=(a&65535)+(e&65535);return(a>>16)+(e>>16)+(b>>16)<<16|b&65535},bit_rol:function(a,e){return a<<e|a>>>32-e},str2binl:function(a){for(var e=[],b=(1<<MD5Helper.chrsz)-1,d=0;d<a.length*MD5Helper.chrsz;d+=MD5Helper.chrsz)e[d>>5]|=(a.charCodeAt(d/MD5Helper.chrsz)&b)<<d%32;return e},binl2str:function(a){for(var e="",
b=(1<<MD5Helper.chrsz)-1,d=0;d<32*a.length;d+=MD5Helper.chrsz)e+=String.fromCharCode(a[d>>5]>>>d%32&b);return e},binl2hex:function(a){for(var e=MD5Helper.hexcase?"0123456789ABCDEF":"0123456789abcdef",b="",d=0;d<4*a.length;d++)b+=e.charAt(a[d>>2]>>d%4*8+4&15)+e.charAt(a[d>>2]>>d%4*8&15);return b},binl2b64:function(a){for(var e="",b=0;b<4*a.length;b+=3)for(var d=(a[b>>2]>>b%4*8&255)<<16|(a[b+1>>2]>>(b+1)%4*8&255)<<8|a[b+2>>2]>>(b+2)%4*8&255,c=0;4>c;c++)e=8*b+6*c>32*a.length?e+MD5Helper.b64pad:e+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(d>>
6*(3-c)&63);return e}};var host=window.location.href;if(0<=host.indexOf("playerhk.jsp")||0<=host.indexOf("Q.jsp"))ContentScript.onInit();